package com.example.util

import com.example.model.Language

object AppStrings {
    fun get(key: String, language: Language): String {
        val map = if (language == Language.ARABIC) ARABIC_STRINGS else ENGLISH_STRINGS
        return map[key] ?: ENGLISH_STRINGS[key] ?: key
    }

    private val ARABIC_STRINGS = mapOf(
        "app_title" to "Pro Calculator",
        "calculator" to "الحاسبة",
        "basic" to "أساسية",
        "scientific" to "علمية",
        "converter" to "المحولات",
        "finance" to "المالية",
        "math" to "الرياضيات",
        "history" to "السجل",
        "favorites" to "المفضلة",
        "settings" to "الإعدادات",
        "clear_all" to "مسح الكل",
        "clear_history" to "مسح السجل",
        "clear_history_confirm" to "هل تريد حقاً مسح سجل العمليات كاملاً؟",
        "delete" to "حذف",
        "cancel" to "إلغاء",
        "confirm" to "تأكيد",
        "save" to "حفظ",
        "copy" to "نسخ",
        "copied" to "تم النسخ بنجاح",
        "share" to "مشاركة",
        "reuse" to "استخدام في الحاسبة",
        "add_favorite" to "إضافة للمفضلة",
        "edit_favorite" to "تعديل المفضلة",
        "title" to "العنوان",
        "note" to "ملاحظة (اختياري)",
        "no_history" to "لا يوجد سجل عمليات بعد",
        "no_history_hint" to "قم بإجراء أي عملية حسابية وسيتم حفظها هنا تلقائياً",
        "no_favorites" to "لا توجد عمليات مفضلة بعد",
        "no_favorites_hint" to "اضغط على أيقونة النجمة لحفظ العمليات المهمة للرجوع إليها",
        
        // Errors
        "error_division_by_zero" to "لا يمكن القسمة على صفر",
        "error_invalid_input" to "صيغة غير صالحة",
        "error_domain" to "قيمة خارج المجال الرياضي",
        "error_syntax" to "تعبير غير مكتمل",
        "error_overflow" to "العدد كبير جداً",

        // Scientific buttons
        "deg" to "درجة (DEG)",
        "rad" to "راديان (RAD)",
        "sin" to "sin",
        "cos" to "cos",
        "tan" to "tan",
        "sinh" to "sinh",
        "cosh" to "cosh",
        "tanh" to "tanh",
        "asin" to "asin",
        "acos" to "acos",
        "atan" to "atan",
        "log" to "log",
        "ln" to "ln",
        "sqrt" to "√",
        "cbrt" to "∛",
        "power" to "^",
        "sqr" to "x²",
        "cube" to "x³",
        "inv" to "1/x",
        "abs" to "|x|",
        "fact" to "x!",
        "pi" to "π",
        "e" to "e",
        "euler" to "γ",
        "mod" to "mod",

        // Unit Converter
        "length" to "الطول",
        "mass" to "الوزن والكتلة",
        "area" to "المساحة",
        "volume" to "الحجم",
        "speed" to "السرعة",
        "time" to "الزمن",
        "temperature" to "درجة الحرارة",
        "storage" to "البيانات الرقمية",
        "angle" to "الزوايا",
        "currency" to "العملات",
        "from" to "من",
        "to" to "إلى",
        "swap" to "تبديل",
        "all_conversions" to "جدول التحويلات الشامل",
        "currency_note" to "تحويل العملات بأسعار الصرف المرجعية - واجهة جاهزة لربط API الخارجي",

        // Finance
        "simple_interest" to "الفائدة البسيطة",
        "compound_interest" to "الفائدة المركبة",
        "discount" to "حساب الخصم",
        "tax" to "الضريبة / القيمة المضافة",
        "percent_change" to "نسبة التغير (زيادة/نقصان)",
        "loan_emi" to "القسط الشهري والقروض",
        "principal" to "المبلغ الأصلي / رأس المال",
        "interest_rate" to "معدل الفائدة السنوي (%)",
        "time_years" to "المدة (سنوات)",
        "time_months" to "المدة (أشهر)",
        "compound_freq" to "تكرار الفائدة في السنة",
        "original_price" to "السعر الأصلي",
        "discount_percent" to "نسبة الخصم (%)",
        "extra_discount" to "خصم إضافي / كوبون (%)",
        "final_price" to "السعر النهائي بعد الخصم",
        "you_save" to "قيمة التوفير",
        "amount" to "المبلغ",
        "tax_rate" to "نسبة الضريبة (%)",
        "tax_included" to "السعر شامل الضريبة",
        "tax_excluded" to "السعر غير شامل الضريبة",
        "net_amount" to "المبلغ الصافي",
        "tax_amount" to "قيمة الضريبة",
        "gross_amount" to "المبلغ الإجمالي",
        "old_value" to "القيمة السابقة / الأصلية",
        "new_value" to "القيمة الجديدة",
        "increase" to "زيادة",
        "decrease" to "نقصان",
        "difference" to "الفرق المطلق",
        "loan_amount" to "مبلغ القرض / التمويل",
        "monthly_payment" to "القسط الشهري (EMI)",
        "total_interest" to "إجمالي الفوائد",
        "total_payable" to "إجمالي المبلغ المستحق",

        // Math & Geometry
        "statistics" to "الإحصاء والمتوسط",
        "enter_numbers_hint" to "أدخل الأرقام مفصولة بفواصل أو مسافات (مثال: 12, 18.5, 4, 9)",
        "mean" to "المتوسط الحسابي (Mean)",
        "median" to "الوسيط (Median)",
        "mode" to "المنوال (Mode)",
        "std_dev" to "الانحراف المعياري (Std Dev)",
        "variance" to "التباين (Variance)",
        "sum" to "المجموع",
        "min" to "أصغر قيمة",
        "max" to "أكبر قيمة",
        "count" to "عدد العناصر",
        "ratio_proportion" to "النسبة والتناسب",
        "ratio_formula" to "A : B = C : X",
        "find_missing" to "حل للمتغير المجهول",
        "lcm_gcd" to "LCM و GCD",
        "enter_two_or_more" to "أدخل رقمين أو أكثر",
        "lcm" to "المضاعف المشترك الأصغر (LCM)",
        "gcd" to "القاسم المشترك الأكبر (GCD)",
        "prime_numbers" to "الأعداد الأولية",
        "enter_integer" to "أدخل عدداً صحيحاً",
        "is_prime" to "هل العدد أولي؟",
        "yes_prime" to "نعم، عدد أولي",
        "not_prime" to "لا، ليس عدداً أولياً",
        "next_prime" to "العدد الأولي التالي",
        "prev_prime" to "العدد الأولي السابق",
        "factors" to "عوامل العدد",
        "prime_factors" to "التحليل للعوامل الأولية",
        "perm_comb" to "التباديل والتوافيق",
        "total_n" to "إجمالي العناصر (n)",
        "choose_r" to "العناصر المختارة (r)",
        "permutations" to "التباديل nPr",
        "combinations" to "التوافيق nCr",
        "trigonometry" to "حساب المثلثات",
        "right_triangle" to "المثلث قائم الزاوية",
        "side_a" to "الضلع a",
        "side_b" to "الضلع b",
        "hypotenuse_c" to "الوتر c",
        "angle_A" to "الزاوية A",
        "angle_B" to "الزاوية B",
        "geometry" to "الأشكال الهندسية",
        "shape" to "اختر الشكل",
        "square" to "مربع",
        "rectangle" to "مستطيل",
        "circle" to "دائرة",
        "triangle" to "مثلث",
        "cylinder" to "أسطوانة",
        "sphere" to "كرة",
        "cone" to "مخروط",
        "cube" to "مكعب",
        "perimeter" to "المحيط",
        "surface_area" to "المساحة السطحية",
        "fractions" to "حساب الكسور",
        "fraction_1" to "الكسر الأول (بسط / مقام)",
        "fraction_2" to "الكسر الثاني (بسط / مقام)",
        "simplified" to "الكسر المبسط",
        "mixed_number" to "العدد الكسري",
        "decimal_value" to "القيمة العشرية",

        // Settings
        "app_settings" to "إعدادات التطبيق",
        "appearance" to "المظهر والتخصيص",
        "theme" to "وضع المظهر",
        "accent_color" to "لون الواجهة والتمييز",
        "button_style" to "شكل الأزرار",
        "haptics_sound" to "الصوت والاهتزاز",
        "haptic_feedback" to "الاهتزاز اللمسي",
        "sound_feedback" to "صوت النقر على الأزرار",
        "calculation_precision" to "دقة الحسابات وعرض الأرقام",
        "decimal_places" to "عدد المنازل العشرية",
        "thousands_sep" to "فاصلة الآلاف",
        "angle_unit" to "وحدة قياس الزوايا الافتراضية",
        "language_choice" to "اللغة / Language",
        "reset_settings" to "إعادة ضبط الإعدادات الافتراضية",
        "reset_confirm" to "هل تريد إعادة تعيين جميع الإعدادات إلى الوضع الافتراضي؟",
        "version_info" to "Pro Calculator v1.0 • حاسبة احترافية متكاملة"
    )

    private val ENGLISH_STRINGS = mapOf(
        "app_title" to "Pro Calculator",
        "calculator" to "Calculator",
        "basic" to "Basic",
        "scientific" to "Scientific",
        "converter" to "Converter",
        "finance" to "Finance",
        "math" to "Math & Geo",
        "history" to "History",
        "favorites" to "Favorites",
        "settings" to "Settings",
        "clear_all" to "Clear All",
        "clear_history" to "Clear History",
        "clear_history_confirm" to "Are you sure you want to clear all calculation history?",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "confirm" to "Confirm",
        "save" to "Save",
        "copy" to "Copy",
        "copied" to "Copied to clipboard",
        "share" to "Share",
        "reuse" to "Use in Calculator",
        "add_favorite" to "Add to Favorites",
        "edit_favorite" to "Edit Favorite",
        "title" to "Title",
        "note" to "Note (Optional)",
        "no_history" to "No history yet",
        "no_history_hint" to "Perform calculations and they will be saved here automatically",
        "no_favorites" to "No favorites saved",
        "no_favorites_hint" to "Tap the star icon on any calculation to save it here",

        // Errors
        "error_division_by_zero" to "Cannot divide by zero",
        "error_invalid_input" to "Invalid expression",
        "error_domain" to "Value outside mathematical domain",
        "error_syntax" to "Incomplete expression",
        "error_overflow" to "Number overflow",

        // Scientific buttons
        "deg" to "Degrees (DEG)",
        "rad" to "Radians (RAD)",
        "sin" to "sin",
        "cos" to "cos",
        "tan" to "tan",
        "sinh" to "sinh",
        "cosh" to "cosh",
        "tanh" to "tanh",
        "asin" to "asin",
        "acos" to "acos",
        "atan" to "atan",
        "log" to "log",
        "ln" to "ln",
        "sqrt" to "√",
        "cbrt" to "∛",
        "power" to "^",
        "sqr" to "x²",
        "cube" to "x³",
        "inv" to "1/x",
        "abs" to "|x|",
        "fact" to "x!",
        "pi" to "π",
        "e" to "e",
        "euler" to "γ",
        "mod" to "mod",

        // Unit Converter
        "length" to "Length",
        "mass" to "Weight & Mass",
        "area" to "Area",
        "volume" to "Volume",
        "speed" to "Speed",
        "time" to "Time",
        "temperature" to "Temperature",
        "storage" to "Digital Storage",
        "angle" to "Angles",
        "currency" to "Currency",
        "from" to "From",
        "to" to "To",
        "swap" to "Swap",
        "all_conversions" to "Comprehensive Conversion Table",
        "currency_note" to "Standard reference exchange rates - API integration ready",

        // Finance
        "simple_interest" to "Simple Interest",
        "compound_interest" to "Compound Interest",
        "discount" to "Discount",
        "tax" to "Sales Tax / VAT",
        "percent_change" to "Percentage Change",
        "loan_emi" to "Loan / EMI Calculator",
        "principal" to "Principal Amount",
        "interest_rate" to "Annual Interest Rate (%)",
        "time_years" to "Duration (Years)",
        "time_months" to "Duration (Months)",
        "compound_freq" to "Compounding Frequency (Per Year)",
        "original_price" to "Original Price",
        "discount_percent" to "Discount Rate (%)",
        "extra_discount" to "Additional Discount (%)",
        "final_price" to "Final Price",
        "you_save" to "Total Savings",
        "amount" to "Amount",
        "tax_rate" to "Tax Rate (%)",
        "tax_included" to "Tax Included (Gross)",
        "tax_excluded" to "Tax Excluded (Net)",
        "net_amount" to "Net Amount",
        "tax_amount" to "Tax Amount",
        "gross_amount" to "Gross Amount",
        "old_value" to "Original Value",
        "new_value" to "New Value",
        "increase" to "Increase",
        "decrease" to "Decrease",
        "difference" to "Absolute Difference",
        "loan_amount" to "Loan Amount",
        "monthly_payment" to "Monthly Payment (EMI)",
        "total_interest" to "Total Interest",
        "total_payable" to "Total Payable Amount",

        // Math & Geometry
        "statistics" to "Statistics & Mean",
        "enter_numbers_hint" to "Enter comma or space separated numbers (e.g., 12, 18.5, 4, 9)",
        "mean" to "Arithmetic Mean",
        "median" to "Median",
        "mode" to "Mode",
        "std_dev" to "Standard Deviation",
        "variance" to "Variance",
        "sum" to "Sum",
        "min" to "Minimum",
        "max" to "Maximum",
        "count" to "Count",
        "ratio_proportion" to "Ratio & Proportion",
        "ratio_formula" to "A : B = C : X",
        "find_missing" to "Solve for missing variable",
        "lcm_gcd" to "LCM & GCD",
        "enter_two_or_more" to "Enter two or more integers",
        "lcm" to "Least Common Multiple (LCM)",
        "gcd" to "Greatest Common Divisor (GCD)",
        "prime_numbers" to "Prime Numbers",
        "enter_integer" to "Enter an integer",
        "is_prime" to "Is it Prime?",
        "yes_prime" to "Yes, Prime number",
        "not_prime" to "No, Composite number",
        "next_prime" to "Next Prime",
        "prev_prime" to "Previous Prime",
        "factors" to "Divisors / Factors",
        "prime_factors" to "Prime Factorization",
        "perm_comb" to "Permutations & Combinations",
        "total_n" to "Total items (n)",
        "choose_r" to "Chosen items (r)",
        "permutations" to "Permutations (nPr)",
        "combinations" to "Combinations (nCr)",
        "trigonometry" to "Trigonometry Solver",
        "right_triangle" to "Right Triangle Solver",
        "side_a" to "Side a",
        "side_b" to "Side b",
        "hypotenuse_c" to "Hypotenuse c",
        "angle_A" to "Angle A",
        "angle_B" to "Angle B",
        "geometry" to "Geometry & Shapes",
        "shape" to "Choose Shape",
        "square" to "Square",
        "rectangle" to "Rectangle",
        "circle" to "Circle",
        "triangle" to "Triangle",
        "cylinder" to "Cylinder",
        "sphere" to "Sphere",
        "cone" to "Cone",
        "cube" to "Cube",
        "perimeter" to "Perimeter / Circumference",
        "surface_area" to "Surface Area",
        "fractions" to "Fraction Calculator",
        "fraction_1" to "Fraction 1 (Num / Denom)",
        "fraction_2" to "Fraction 2 (Num / Denom)",
        "simplified" to "Simplified Fraction",
        "mixed_number" to "Mixed Number",
        "decimal_value" to "Decimal Value",

        // Settings
        "app_settings" to "Application Settings",
        "appearance" to "Appearance & Customization",
        "theme" to "Theme Mode",
        "accent_color" to "Accent Color",
        "button_style" to "Button Style",
        "haptics_sound" to "Sound & Haptics",
        "haptic_feedback" to "Haptic Feedback (Vibration)",
        "sound_feedback" to "Button Click Sound",
        "calculation_precision" to "Precision & Formatting",
        "decimal_places" to "Decimal Places",
        "thousands_sep" to "Thousands Separator",
        "angle_unit" to "Default Angle Unit",
        "language_choice" to "Language / اللغة",
        "reset_settings" to "Reset to Defaults",
        "reset_confirm" to "Reset all settings to default values?",
        "version_info" to "Pro Calculator v1.0 • Professional All-in-One Calculator"
    )
}
